baseURL = "https://anumamadsiddiqui.github.io/aneng.github.io/"
languageCode = "en-gb"
title = "Hi, I'm Anum"
theme = "PaperMod"

relativeURLs = true
canonifyURLs = true

[params]
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    hideFooter = true
    ShowAuthor = false
    disableThemeToggle = false